---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/movies":
    get:
      summary: list movies
      tags:
      - Movies
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: successful
  "/movies/{id}":
    get:
      summary: show movie
      tags:
      - Movies
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        type: string
        description: id
        required: true
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: successful
  "/movies/{id}/reviews":
    post:
      summary: create a review movie
      tags:
      - Reviews
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        type: string
        description: id
        required: true
      - name: Authorization
        in: header
        type: string
        required: true
      - name: review
        in: body
        schema:
          type: object
          properties:
            review:
              type: object
              properties:
                content:
                  type: string
                rating:
                  type: decimal
          required:
          - content
          - rating
      responses:
        '201':
          description: review created
    get:
      summary: get movie reviews
      tags:
      - Reviews
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        type: string
        description: id
        required: true
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: review list
  "/users/reviews":
    get:
      summary: get user reviews
      tags:
      - Reviews
      consumes:
      - application/json
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: user reviews list
  "/sessions":
    post:
      summary: Log in
      tags:
      - Users
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          required:
          - email
          - password
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
  "/users":
    post:
      summary: Create user
      tags:
      - Users
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
          required:
          - username
          - email
          - password
          - password_confirmation
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
